-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PROJECT_FOOTBALL
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PROJECT_FOOTBALL` ;

-- -----------------------------------------------------
-- Schema PROJECT_FOOTBALL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PROJECT_FOOTBALL` DEFAULT CHARACTER SET utf8 ;
USE `PROJECT_FOOTBALL` ;

-- -----------------------------------------------------
-- Table `PROJECT_FOOTBALL`.`EQUIPOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT_FOOTBALL`.`EQUIPOS` (
  `idEQUIPOS` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `CIUDAD` VARCHAR(45) NOT NULL,
  `ESTADIO` VARCHAR(45) NOT NULL,
  `FUNDACION` DATE NOT NULL,
  PRIMARY KEY (`idEQUIPOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROJECT_FOOTBALL`.`JUGADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT_FOOTBALL`.`JUGADORES` (
  `idJUGADORES` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `EDAD` INT NOT NULL,
  `NACIONALIDAD` VARCHAR(45) NOT NULL,
  `POSICION` VARCHAR(45) NOT NULL,
  `GOLES` INT NOT NULL,
  `ASISTENCIAS` INT NOT NULL,
  `TARGETAS_AMARILLAS` INT NOT NULL,
  `TARGETAS_ROJAS` INT NOT NULL,
  `EQUIPOS_idEQUIPOS` INT NOT NULL,
  PRIMARY KEY (`idJUGADORES`),
  INDEX `fk_JUGADORES_EQUIPOS_idx` (`EQUIPOS_idEQUIPOS` ASC) VISIBLE,
  CONSTRAINT `fk_JUGADORES_EQUIPOS`
    FOREIGN KEY (`EQUIPOS_idEQUIPOS`)
    REFERENCES `PROJECT_FOOTBALL`.`EQUIPOS` (`idEQUIPOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROJECT_FOOTBALL`.`PARTIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT_FOOTBALL`.`PARTIDOS` (
  `idPARTIDOS` INT NOT NULL AUTO_INCREMENT,
  `FEACH` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `GOLES_LOCALES` INT NOT NULL,
  `GOLES_VISITANTES` INT NOT NULL,
  `EQUIPOS_idEQUIPOS_LOCAL` INT NOT NULL,
  `EQUIPOS_idEQUIPOS1_VISIT` INT NOT NULL,
  PRIMARY KEY (`idPARTIDOS`),
  INDEX `fk_PARTIDOS_EQUIPOS1_idx` (`EQUIPOS_idEQUIPOS_LOCAL` ASC) VISIBLE,
  INDEX `fk_PARTIDOS_EQUIPOS2_idx` (`EQUIPOS_idEQUIPOS1_VISIT` ASC) VISIBLE,
  CONSTRAINT `fk_PARTIDOS_EQUIPOS1`
    FOREIGN KEY (`EQUIPOS_idEQUIPOS_LOCAL`)
    REFERENCES `PROJECT_FOOTBALL`.`EQUIPOS` (`idEQUIPOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTIDOS_EQUIPOS2`
    FOREIGN KEY (`EQUIPOS_idEQUIPOS1_VISIT`)
    REFERENCES `PROJECT_FOOTBALL`.`EQUIPOS` (`idEQUIPOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROJECT_FOOTBALL`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT_FOOTBALL`.`USUARIOS` (
  `idUSUARIOS` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `CORREO` VARCHAR(45) NOT NULL,
  `ROL` TINYINT NOT NULL,
  PRIMARY KEY (`idUSUARIOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROJECT_FOOTBALL`.`TORNEOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT_FOOTBALL`.`TORNEOS` (
  `idTORNEOS` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_INICIO` DATE NOT NULL,
  `FECH_FIN` DATE NOT NULL,
  `USUARIOS_idUSUARIOS` INT NOT NULL,
  PRIMARY KEY (`idTORNEOS`),
  INDEX `fk_TORNEOS_USUARIOS1_idx` (`USUARIOS_idUSUARIOS` ASC) VISIBLE,
  CONSTRAINT `fk_TORNEOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_idUSUARIOS`)
    REFERENCES `PROJECT_FOOTBALL`.`USUARIOS` (`idUSUARIOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROJECT_FOOTBALL`.`PARTICIPACION_TORNEOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT_FOOTBALL`.`PARTICIPACION_TORNEOS` (
  `idPARTICIPACION_TORNEOS` INT NOT NULL AUTO_INCREMENT,
  `EQUIPOS_idEQUIPOS1` INT NOT NULL,
  `TORNEOS_idTORNEOS` INT NOT NULL,
  PRIMARY KEY (`idPARTICIPACION_TORNEOS`),
  INDEX `fk_PARTICIPACION_TORNEOS_EQUIPOS2_idx` (`EQUIPOS_idEQUIPOS1` ASC) VISIBLE,
  INDEX `fk_PARTICIPACION_TORNEOS_TORNEOS1_idx` (`TORNEOS_idTORNEOS` ASC) VISIBLE,
  CONSTRAINT `fk_PARTICIPACION_TORNEOS_EQUIPOS2`
    FOREIGN KEY (`EQUIPOS_idEQUIPOS1`)
    REFERENCES `PROJECT_FOOTBALL`.`EQUIPOS` (`idEQUIPOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTICIPACION_TORNEOS_TORNEOS1`
    FOREIGN KEY (`TORNEOS_idTORNEOS`)
    REFERENCES `PROJECT_FOOTBALL`.`TORNEOS` (`idTORNEOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROJECT_FOOTBALL`.`TEMPORADAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT_FOOTBALL`.`TEMPORADAS` (
  `idTEMPORADAS` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `FECHA_INICIO` DATE NOT NULL,
  `FECHA_FIN` DATE NOT NULL,
  PRIMARY KEY (`idTEMPORADAS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROJECT_FOOTBALL`.`EQUIPOS_TEMPORADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROJECT_FOOTBALL`.`EQUIPOS_TEMPORADA` (
  `PUNTOS` INT NOT NULL,
  `PARTIDOS_GANADOS` INT NOT NULL,
  `PARTIDOS_EMPATADOS` INT NOT NULL,
  `PARTIDOS_PERDIDOS` INT NOT NULL,
  `EQUIPOS_idEQUIPOS` INT NOT NULL,
  `TEMPORADAS_idTEMPORADAS` INT NOT NULL,
  INDEX `fk_EQUIPOS_TEMPORADA_EQUIPOS1_idx` (`EQUIPOS_idEQUIPOS` ASC) VISIBLE,
  INDEX `fk_EQUIPOS_TEMPORADA_TEMPORADAS1_idx` (`TEMPORADAS_idTEMPORADAS` ASC) VISIBLE,
  CONSTRAINT `fk_EQUIPOS_TEMPORADA_EQUIPOS1`
    FOREIGN KEY (`EQUIPOS_idEQUIPOS`)
    REFERENCES `PROJECT_FOOTBALL`.`EQUIPOS` (`idEQUIPOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EQUIPOS_TEMPORADA_TEMPORADAS1`
    FOREIGN KEY (`TEMPORADAS_idTEMPORADAS`)
    REFERENCES `PROJECT_FOOTBALL`.`TEMPORADAS` (`idTEMPORADAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
